services:
  poll_app:
    build: ./polls
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./polls:/app
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - mongodb

  question_app:
    build: ./question
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8002"
    volumes:
      - ./question:/app
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - mongodb

  vote_app:
    build: ./vote
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8003"
    volumes:
      - ./vote:/app
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: mongo:7.0
    ports:
      - "27017:27017"

  nginx:
    build: ./conf
    ports:
      - "80:80"
    depends_on:
      - poll_app
      - question_app
      - vote_app
